import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { DashboardWrapper } from "@/components/DashboardWrapper";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardWrapper>
          <Navbar />
          {children}
        </DashboardWrapper>
      </body>
    </html>
  );
}
